# Generated by Django 4.2.11 on 2024-09-09 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_collectionsnapshot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collectionsnapshot',
            old_name='new',
            new_name='new_count',
        ),
        migrations.RenameField(
            model_name='collectionsnapshot',
            old_name='notes',
            new_name='notes_count',
        ),
        migrations.RemoveField(
            model_name='collectionsnapshot',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='collectionsnapshot',
            name='partly_paid',
        ),
        migrations.AddField(
            model_name='collectionsnapshot',
            name='paid_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='collectionsnapshot',
            name='partly_paid_count',
            field=models.IntegerField(default=0),
        ),
    ]
