# Generated by Django 4.2.11 on 2024-09-30 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_rename_new_collectionsnapshot_new_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionsnapshot',
            name='amount_paid_rate',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='collectionsnapshot',
            name='paid_rate',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
