# Generated by Django 4.2.11 on 2024-05-09 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default='08147173448', max_length=11, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='stage',
            field=models.IntegerField(default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='stage_id',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.CharField(default='collector', max_length=10),
        ),
    ]
