# Generated by Django 4.2.11 on 2024-05-09 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_user_phone_user_stage_user_stage_id_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='stage',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='stage_id',
            field=models.IntegerField(default=1),
        ),
    ]
