# Generated by Django 4.2.11 on 2024-06-15 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0006_user_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='project',
        ),
    ]
