# Generated by Django 4.2.11 on 2024-06-15 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_pack', '0002_project_created_at'),
        ('admin_panel', '0007_remove_user_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='project_pack.project'),
            preserve_default=False,
        ),
    ]
