# Generated by Django 4.2.11 on 2024-06-23 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0009_recovery'),
    ]

    operations = [
        migrations.AddField(
            model_name='waive',
            name='reason',
            field=models.CharField(default='PP', max_length=10),
        ),
        migrations.AlterField(
            model_name='collection',
            name='amount_due',
            field=models.FloatField(default=0, max_length=15),
        ),
    ]
