# Generated by Django 4.2.11 on 2024-06-27 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0010_waive_reason_alter_collection_amount_due'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanstatic',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
