# Generated by Django 4.2.11 on 2024-06-28 12:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0008_loan_interest_perc'),
        ('admin_panel', '0011_alter_loanstatic_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='repayment',
            name='overdue_days',
            field=models.IntegerField(default=0, max_length=10),
        ),
        migrations.CreateModel(
            name='Blacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(default='overdue', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan_app.appuser')),
            ],
        ),
    ]
