# Generated by Django 4.2.11 on 2024-06-28 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0012_repayment_overdue_days_blacklist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blacklist',
        ),
    ]
