# Generated by Django 4.2.11 on 2024-06-28 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0013_delete_blacklist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repayment',
            name='overdue_days',
            field=models.IntegerField(default=0),
        ),
    ]
