# Generated by Django 4.2.11 on 2024-07-17 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0014_alter_repayment_overdue_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='repayment',
            name='tx_ref',
            field=models.CharField(default='', max_length=50),
        ),
    ]
