# Generated by Django 4.2.11 on 2024-07-18 07:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0010_loan_decline_reason_alter_blacklist_user'),
        ('admin_panel', '0015_repayment_tx_ref'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repayment',
            old_name='tx_ref',
            new_name='tx_id',
        ),
        migrations.CreateModel(
            name='PendingDisbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan_app.loan')),
            ],
        ),
    ]
