# Generated by Django 4.2.11 on 2024-07-18 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0010_loan_decline_reason_alter_blacklist_user'),
        ('admin_panel', '0016_rename_tx_ref_repayment_tx_id_pendingdisbursement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingdisbursement',
            name='loan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='loan_app.loan'),
        ),
    ]
