# Generated by Django 4.2.11 on 2024-07-18 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0017_alter_pendingdisbursement_loan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PendingDisbursement',
        ),
    ]
