# Generated by Django 4.2.11 on 2024-05-16 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0017_repayment_loanstatic_collection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repayment',
            old_name='amount_held',
            new_name='amount_loaned',
        ),
        migrations.RenameField(
            model_name='repayment',
            old_name='amount_paid',
            new_name='amount_paid_now',
        ),
        migrations.AddField(
            model_name='repayment',
            name='repayment_amount',
            field=models.FloatField(default=0, max_length=10),
        ),
    ]
