# Generated by Django 4.2.11 on 2024-05-16 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0018_rename_amount_held_repayment_amount_loaned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='super',
            field=models.BooleanField(default=False),
        ),
    ]
