# Generated by Django 4.2.11 on 2024-07-19 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0019_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='status',
            field=models.CharField(default='info', max_length=20),
        ),
    ]
