# Generated by Django 4.2.11 on 2024-05-16 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0019_note_super'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='stage',
            field=models.IntegerField(default=0),
        ),
    ]
