# Generated by Django 4.2.11 on 2024-07-19 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0020_logs_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='fee',
            field=models.FloatField(default=0),
        ),
    ]
