# Generated by Django 4.2.11 on 2024-05-27 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0020_alter_collection_stage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repayment',
            old_name='amount_loaned',
            new_name='amount_due',
        ),
        migrations.RenameField(
            model_name='repayment',
            old_name='repayment_amount',
            new_name='principal_amount',
        ),
    ]
