# Generated by Django 4.2.11 on 2024-07-20 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0021_logs_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='repayment',
            name='status',
            field=models.CharField(default='', max_length=10),
        ),
    ]
