# Generated by Django 4.2.11 on 2024-07-20 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0022_repayment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='repayment',
            name='allow',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='AcceptedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
