# Generated by Django 4.2.11 on 2024-05-31 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0023_progressive_a_count_reloan_progressive_a_sum_reloan_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='amount_held',
            new_name='amount_due',
        ),
        migrations.AddField(
            model_name='user',
            name='can_collect',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='stage',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='stage',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
