# Generated by Django 4.2.11 on 2024-06-01 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0023_loan_reloan'),
        ('admin_panel', '0025_collection_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Waive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waive_amount', models.FloatField(default=0, max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=10)),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('app_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan_app.appuser')),
                ('loan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='loan_app.loan')),
            ],
        ),
    ]
