# Generated by Django 4.2.11 on 2024-06-01 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0027_alter_user_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waive',
            name='app_user',
        ),
    ]
