# Generated by Django 4.2.11 on 2024-06-04 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0030_timeline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline',
            name='detail',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='overdue_days',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
