# Generated by Django 4.2.11 on 2024-06-05 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0031_alter_timeline_detail_alter_timeline_overdue_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repayment',
            name='stage',
            field=models.CharField(default='A', max_length=10),
        ),
    ]
