# Generated by Django 4.2.11 on 2024-06-06 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0024_loan_repaid_at'),
        ('admin_panel', '0032_alter_repayment_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='loan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='loan_app.loan'),
        ),
    ]
