# Generated by Django 4.2.11 on 2024-08-03 20:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project_pack', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('username', models.CharField(default='', max_length=15)),
                ('phone2', models.CharField(blank=True, default='', max_length=15, null=True)),
                ('bvn', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('email2', models.EmailField(blank=True, default='', max_length=254, null=True)),
                ('address', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('status', models.BooleanField(default=False)),
                ('status_reason', models.TextField(default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_access', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_id', models.CharField(max_length=20)),
                ('dob', models.DateField(default=django.utils.timezone.now)),
                ('password', models.CharField(max_length=100)),
                ('gender', models.CharField(default='male', max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('lga', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('eligible_amount', models.FloatField(default=10000)),
                ('marital_status', models.CharField(default='', max_length=100)),
                ('nationality', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('children', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('education', models.CharField(default='', max_length=100)),
                ('employment', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('borrow_level', models.IntegerField(default=1)),
                ('suspend', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_pack.project')),
            ],
        ),
        migrations.CreateModel(
            name='VirtualAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_code', models.CharField(blank=True, max_length=100, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_pack.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan_app.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='SmsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan_app.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='loan_app.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('message_type', models.CharField(default='system', max_length=20)),
                ('viewed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan_app.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_id', models.CharField(max_length=100)),
                ('principal_amount', models.FloatField(default=0, max_length=10)),
                ('amount_disbursed', models.FloatField(default=0, max_length=10)),
                ('amount_due', models.FloatField(default=0, max_length=10)),
                ('amount_paid', models.FloatField(default=0, max_length=10)),
                ('duration', models.IntegerField(default=5)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('disbursed_at', models.DateTimeField(blank=True, null=True)),
                ('repaid_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=100)),
                ('reloan', models.IntegerField(default=1)),
                ('interest_perc', models.FloatField(default=40)),
                ('decline_reason', models.TextField(blank=True, null=True)),
                ('disburse_id', models.CharField(default='', max_length=20)),
                ('purpose', models.CharField(default='', max_length=100)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_pack.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan_app.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='loan_app/docs/')),
                ('name', models.CharField(default='', max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan_app.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='DisbursementAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_code', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='loan_app.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(max_length=100)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan_app.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(max_length=100)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('timestamp', models.CharField(default='', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan_app.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='Blacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(default='overdue', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='loan_app.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(blank=True, null=True, upload_to='loan_app/avatar/')),
                ('name', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='Profile Image', max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='loan_app.appuser')),
            ],
        ),
    ]
