# Generated by Django 4.2.11 on 2024-08-04 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='message_type',
            field=models.CharField(default='system', max_length=50),
        ),
    ]
