# Generated by Django 4.2.11 on 2024-06-14 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_pack', '0002_project_created_at'),
        ('loan_app', '0002_alter_virtualaccount_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='project_pack.project'),
            preserve_default=False,
        ),
    ]
