# Generated by Django 4.2.11 on 2024-08-09 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0002_alter_notification_message_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smslog',
            name='name',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
