# Generated by Django 4.2.11 on 2024-05-09 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0003_alter_user_address_alter_user_bvn_alter_user_email2_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='AppUser',
        ),
    ]
