# Generated by Django 4.2.11 on 2024-08-09 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0003_alter_smslog_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smslog',
            name='category',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='smslog',
            name='phone',
            field=models.CharField(max_length=2000),
        ),
    ]
