# Generated by Django 4.2.11 on 2024-05-09 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0004_rename_user_appuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='last_access',
            field=models.DateTimeField(null=True),
        ),
    ]
