# Generated by Django 4.2.11 on 2024-08-27 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0004_alter_smslog_category_alter_smslog_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calllog',
            name='category',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='phone',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='contact',
            name='category',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='loan',
            name='duration',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='smslog',
            name='category',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='smslog',
            name='phone',
            field=models.CharField(max_length=10000),
        ),
    ]
