# Generated by Django 4.2.11 on 2024-08-27 20:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0005_alter_calllog_category_alter_calllog_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklist',
            name='reason',
            field=models.CharField(default='default', max_length=100),
        ),
        migrations.CreateModel(
            name='Whitelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='loan_app.appuser')),
            ],
        ),
    ]
