# Generated by Django 4.2.11 on 2024-05-10 08:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0006_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='last_access',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
