# Generated by Django 4.2.11 on 2024-09-30 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0006_alter_blacklist_reason_whitelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='device_id',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
