# Generated by Django 4.2.11 on 2024-05-10 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0007_alter_appuser_last_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='gender',
            field=models.CharField(default='m', max_length=100),
        ),
        migrations.AddField(
            model_name='appuser',
            name='lga',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='state',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='file',
            field=models.ImageField(upload_to='loan_app/avatar/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.ImageField(upload_to='loan_app/docs/'),
        ),
    ]
