# Generated by Django 4.2.11 on 2024-05-10 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0008_appuser_gender_appuser_lga_appuser_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='gender',
            field=models.CharField(default='male', max_length=100),
        ),
    ]
