# Generated by Django 4.2.11 on 2024-05-10 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0009_alter_appuser_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guarantor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan_app.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='Employment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('state', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('address', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('complex', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('role', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('duration', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('salary', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('contact_name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('contact_number', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('contact_email', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='loan_app.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='Emergency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('family_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('family_relationship', models.CharField(blank=True, max_length=100, null=True)),
                ('family_email', models.CharField(blank=True, max_length=100, null=True)),
                ('family_occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('colleague_name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('colleague_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('colleague_email', models.CharField(blank=True, max_length=100, null=True)),
                ('colleague_occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='loan_app.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='DisbursementAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=100, null=True)),
                ('bank', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='loan_app.appuser')),
            ],
        ),
    ]
