# Generated by Django 4.2.11 on 2024-06-28 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0009_blacklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='decline_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blacklist',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='loan_app.appuser'),
        ),
    ]
