# Generated by Django 4.2.11 on 2024-05-11 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0010_guarantor_employment_emergency_disbursementaccount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employment',
            old_name='contact_email',
            new_name='hr_email',
        ),
        migrations.RenameField(
            model_name='employment',
            old_name='contact_name',
            new_name='hr_name',
        ),
        migrations.RenameField(
            model_name='employment',
            old_name='contact_number',
            new_name='hr_number',
        ),
    ]
