# Generated by Django 4.2.11 on 2024-07-18 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0010_loan_decline_reason_alter_blacklist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='disburse_id',
            field=models.CharField(default='', max_length=20),
        ),
    ]
