# Generated by Django 4.2.11 on 2024-05-11 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0011_rename_contact_email_employment_hr_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guarantor',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
