# Generated by Django 4.2.11 on 2024-07-19 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0011_loan_disburse_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='children',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='employment',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='marital_status',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='appuser',
            name='nationality',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
