# Generated by Django 4.2.11 on 2024-05-11 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0012_guarantor_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employment',
            old_name='hr_number',
            new_name='hr_phone',
        ),
    ]
