# Generated by Django 4.2.11 on 2024-07-19 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0012_appuser_children_appuser_employment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='education',
            field=models.CharField(default='', max_length=100),
        ),
    ]
