# Generated by Django 4.2.11 on 2024-05-15 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0013_rename_hr_number_employment_hr_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatar',
            name='description',
            field=models.CharField(default='Profile Image', max_length=100),
        ),
    ]
