# Generated by Django 4.2.11 on 2024-07-19 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0013_appuser_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
