# Generated by Django 4.2.11 on 2024-07-19 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0014_alter_appuser_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='status_reason',
            field=models.TextField(default=''),
        ),
    ]
