# Generated by Django 4.2.11 on 2024-07-20 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0015_appuser_status_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='username',
            field=models.CharField(default='', max_length=15),
        ),
    ]
