# Generated by Django 4.2.11 on 2024-05-16 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0016_loan_approved_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='approved_at',
            new_name='disbursed_at',
        ),
    ]
