# Generated by Django 4.2.11 on 2024-07-20 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0016_appuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
