# Generated by Django 4.2.11 on 2024-05-16 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0017_rename_approved_at_loan_disbursed_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='amount',
            new_name='amount_loaned',
        ),
        migrations.AddField(
            model_name='loan',
            name='repayment_amount',
            field=models.FloatField(default=0, max_length=10),
        ),
    ]
