# Generated by Django 4.2.11 on 2024-07-20 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0017_loan_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='purpose',
            field=models.CharField(default='', max_length=100),
        ),
    ]
