# Generated by Django 4.2.11 on 2024-07-20 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0018_loan_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='borrow_level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='blacklist',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
