# Generated by Django 4.2.11 on 2024-05-16 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0018_rename_amount_loan_amount_loaned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='loan_id',
            field=models.CharField(default='121789', max_length=100),
            preserve_default=False,
        ),
    ]
