# Generated by Django 4.2.11 on 2024-07-20 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0019_appuser_borrow_level_blacklist_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='duration',
            field=models.IntegerField(default=5),
        ),
    ]
