# Generated by Django 4.2.11 on 2024-05-27 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0021_alter_loan_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='amount_loaned',
            new_name='amount_disbursed',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='repayment_amount',
            new_name='amount_due',
        ),
        migrations.AddField(
            model_name='loan',
            name='principal_amount',
            field=models.FloatField(default=0, max_length=10),
        ),
    ]
