# Generated by Django 4.2.11 on 2024-05-28 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0022_rename_amount_loaned_loan_amount_disbursed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='reloan',
            field=models.IntegerField(default=1),
        ),
    ]
