# Generated by Django 4.2.11 on 2024-06-01 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0023_loan_reloan'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='repaid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
