# Generated by Django 4.2.11 on 2024-07-22 08:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0023_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='smslog',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
