# Generated by Django 4.2.11 on 2024-07-23 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0024_smslog_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='suspend',
            field=models.BooleanField(default=False),
        ),
    ]
