# Generated by Django 4.2.11 on 2024-07-23 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0025_appuser_suspend'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatar',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='document',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='loan_app/avatar/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='loan_app/docs/'),
        ),
    ]
