# Generated by Django 4.2.11 on 2024-07-25 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0027_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
