# Generated by Django 4.2.11 on 2024-07-27 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0029_calllog'),
    ]

    operations = [
        migrations.AddField(
            model_name='calllog',
            name='timestamp',
            field=models.CharField(default='', max_length=50),
        ),
    ]
